# Generated by Django 6.0.3 on 2026-05-29 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='地块名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
            ],
            options={
                'verbose_name': '地块',
                'verbose_name_plural': '地块',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='序列号')),
                ('gps_time', models.DateTimeField(verbose_name='GPS时间')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('x', models.FloatField(verbose_name='x坐标')),
                ('y', models.FloatField(verbose_name='y坐标')),
                ('speed', models.FloatField(verbose_name='速度(km/h)')),
                ('heading', models.FloatField(verbose_name='航向')),
                ('working_status', models.BooleanField(verbose_name='工作状态')),
                ('width', models.FloatField(verbose_name='幅宽(m)')),
                ('depth', models.FloatField(verbose_name='深度(mm)')),
                ('depth_standard', models.FloatField(verbose_name='深度标准值')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='tracks.track', verbose_name='地块')),
            ],
            options={
                'verbose_name': '轨迹点',
                'verbose_name_plural': '轨迹点',
                'ordering': ['track', 'sequence'],
                'indexes': [models.Index(fields=['track', 'sequence'], name='tracks_trac_track_i_6d4c3a_idx')],
            },
        ),
    ]
